### PR TITLE
better type for searchFilter function

### PR DESCRIPTION
**Pull request by bogusweb**

### CODE REVIEW

**Comment by bogusweb** [comment]
damn sorry, not here. It was supposed to be on my fork :(

**Comment by manudss** [comment]
Why seems to be a good idea!?

**Comment by bogusweb** [comment]
because you don't always remember what keys you have in the interface
image

**Comment by manudss** [comment]
Yes, it was a good idea, why delete the pull request?

**Comment by bogusweb** [comment]
because `Property 'toLocaleLowerCase' does not exist on type 'T[keyof T & string]'.`. I just clone fork and testing locally. Soon i create a pr.

So far, all I've come up with is the use Map. But its ugly :<
```
export function searchFilterIn<T = Object>( searchKey: string, inObj: T, inKey: keyof T): boolean {
  const objMap = new Map(
    Object.entries(inObj)
  );
  return  isString(searchKey)
    && isString(inKey)
    && isString(objMap.get(inKey))
    && objMap.get(inKey)
    && objMap.get(inKey).toLocaleLowerCase().includes(searchKey.toLocaleLowerCase());
}
```

**Comment by manudss** [comment]
The function with type : 
/**
 * Helper function to do search in one key of an object
 */
export function searchFilterIn<T = Object>( searchKey: string, inObj: T, inKey: keyof T ): boolean {
  return  isString(searchKey)
    && isString(inKey)
    && isString(inObj[inKey])
    && (inObj[inKey] as unknown as string).toLocaleLowerCase().includes(searchKey.toLocaleLowerCase());
}

It is just only search into string elements, so we could add a cast like this !

**Pull request closed without merging**
